import { Inter } from "next/font/google"
import Head from "next/head"
import Header from "@/components/Layout/Header"
import Hero from "@/components/Hero/Hero"
import Layout from "@/components/Layout/Layout"

import styles from "@/styles/Main.module.scss"
import Menu from "@/components/Layout/Menu"
// import styles from "@/styles/Home.module.scss"

const inter = Inter({ subsets: ["latin"] })

export default function Home() {
	return (
		<>
			<Head>
				<title>Информационный портал ЮО ВНГ </title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" type="img/svg" sizes="16x32" href="/logo.svg" />
			</Head>
			{/* <Header /> */}
			{/* <Hero /> */}
			<Layout>
				<Menu />
				<main className={styles.main}>
					<Hero />
				</main>
			</Layout>
		</>
	)
}
